DatingApp/Models/FriendViewModel.cs
using DataLayer.Models;
using System.Collections.Generic;
namespace DatingApp.Models
{
    public class FriendViewModel
    {
        public Person FirstPerson { get; set; }
        public Person SecondPerson { get; set; }

    }

    public class FriendUserViewModel
    {
        public int PersonId { get; set; }
        public List<FriendViewModel> Friends { get; set; }
    }
}

DatingApp/Models/ProfileViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;

namespace DatingApp.Models
{
    public class ProfileViewModel
    {
        public int PersonId { get; set; }

        [Required]
        [DisallowNull]
        [Display(Name = "First name")]
        [RegularExpression(@"^[a-öA-Ö]+$", ErrorMessage = "Enter first name with only letters (A-Ö)")]
        public string FirstName { get; set; }

        [Required]
        [DisallowNull]
        [Display(Name = "Last name")]
        [RegularExpression(@"^[a-öA-Ö]+$", ErrorMessage = "Enter first name with only letters (A-Ö)")]
        public string LastName { get; set; }

        [StringLength(300)]
        public string Description { get; set; }

        public byte[] Picture { get; set; }

        public string Email { get; set; }

        public bool AccountHidden { get; set; }
        public PostUserViewModel Posts { get; set; }
        public FriendUserViewModel Friends { get; set; }
    }
}

DatingApp/Controllers/PersonController.cs
using DataLayer;
using DataLayer.Models;
using DataLayer.Repositories;
using DatingApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;


namespace DatingApp.Controllers
{
    public class PersonController : Controller
    {
        private readonly DatingAppContext _context;
        private PersonRepository personRepository;
        private PostRepository postRepository;
        private FriendRequestRepository requestRepository;

        public PersonController(DatingAppContext context)
        {
            _context = context;
            personRepository = new PersonRepository(context);
            postRepository = new PostRepository(context);
            requestRepository = new FriendRequestRepository(context);
        }

        public IActionResult Profile(int id)
        {
            if (id > 0)
            {
                Person user = personRepository.GetPersonById((int)id);
                List<Post> posts = postRepository.GetAllPostsByPersonId((int)id);
                PostUserViewModel postUserViewModel = CreatePostUserViewModel(posts, (int)id);
                ProfileViewModel profileViewModel = new ProfileViewModel
                {
                    PersonId = user.PersonId,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    Description = user.Description,
                    Picture = user.Picture,
                    Posts = postUserViewModel
                };
                ViewBag.PersonRelation = GetPersonRelation(id);
                return View(profileViewModel);
            }
            //Om vi kommer hit är något fel och vi återgår till startsidan
            return RedirectToAction("Index", "Home");
        }

        //Kollar vilken relation två användare har till varandra för att uppdatera relationsknappen i Profile-vyn
        public string GetPersonRelation(int id)  
        {
            int loggedInUser = personRepository.GetIdByUserIdentityEmail(User.Identity.Name);
            if (requestRepository.IsFriends(loggedInUser, id))
            {
                return "Friends";
            }
            else if (requestRepository.FriendRequestOutgoing(loggedInUser, id))
            {
                return "OutgoingRequest";
            }
            else if (requestRepository.FriendRequestIncoming(loggedInUser, id))
            {
                return "IncomingRequest";
            }
            else
            {
                return "NotFriends";
            }
        }

        //Skapar vymodell - PostUserViewModel, som innehåller de inlägg som gjorts på en användares vägg.
        public PostUserViewModel CreatePostUserViewModel(List<Post> posts, int personId)
        {
            IEnumerable<PostViewModel> postsViewModel = posts.Select((p) => new PostViewModel()
            {
                PostId = p.PostId,
                Author = personRepository.GetPersonById(p.AuthorId),
                PostText = p.PostText,
                Timestamp = p.Timestamp
            });

            PostUserViewModel postUserViewModel = new PostUserViewModel
            {
                PersonId = personId,
                Posts = postsViewModel.ToList()
            };
            return postUserViewModel;
        }

        //Hämtar den inloggade användarens profil, med tillhörande inlägg och vänlista.
        public IActionResult MyProfile()
        {
            string email = User.Identity.Name;
            int id = personRepository.GetIdByUserIdentityEmail((string)email);
            Person user = personRepository.GetPersonById((int)id);
            List<Post> posts = postRepository.GetAllPostsByPersonId((int)id);
            List<FriendRequest> friends = requestRepository.GetFriendsByPersonId((int)id);
            PostUserViewModel postUserViewModel = CreatePostUserViewModel(posts, (int)id);
            FriendUserViewModel friendUserViewModel = CreateFriendUserViewModel(friends, (int)id);
            if (ModelState.IsValid)
            {
                ProfileViewModel profileViewModel = new ProfileViewModel
                {
                    PersonId = user.PersonId,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    Description = user.Description,
                    Picture = user.Picture,
                    Email = user.Email,
                    AccountHidden = user.AccountHidden,
                    Posts = postUserViewModel,
                    Friends = friendUserViewModel
                };
                return View(profileViewModel);
            }
            //Om vi kommer hit är något fel och vi återgår till startsidan
            return RedirectToAction("Index", "Home");
        }

        //Skapar vymodell - FriendUserViewModel, som innehåller den inloggade användarens vänner.
        public FriendUserViewModel CreateFriendUserViewModel(List<FriendRequest> friends, int personId)
        {
            IEnumerable<FriendViewModel> friendsViewModel = friends.Select((p) => new FriendViewModel()
            {
                FirstPerson = personRepository.GetPersonById(p.SenderId),
                SecondPerson = personRepository.GetPersonById(p.ReceiverId)
            });

            FriendUserViewModel friendUserViewModel = new FriendUserViewModel
            {
                PersonId = personId,
                Friends = friendsViewModel.ToList()
            };
            return friendUserViewModel;
        }

        public ActionResult RemoveFriend(int friendToRemove)
        {
            int currentUser = personRepository.GetIdByUserIdentityEmail(User.Identity.Name);
            List<FriendRequest> friends = requestRepository.GetFriendsByPersonId(currentUser);
            foreach (FriendRequest f in friends)
            {
                /*Hämtar den FriendRequest där SenderID och ReceiverID stämmer, och tar bort den, kontroll görs åt båda hållen
                 * - användaren kan nämligen antingen vara den som skickat eller fått vänförfrågan. */
                if (f.ReceiverId.Equals(currentUser) && f.SenderId.Equals(friendToRemove) || f.ReceiverId.Equals(friendToRemove) && f.SenderId.Equals(currentUser))
                {
                    try
                    {
                        _context.Remove(f);
                        _context.SaveChanges();
                    }
                    catch (Exception)
                    {
                        TempData["ProcessMessage"] = "Could not remove friend, try again later";
                        return PartialView("Exception");
                    }
                    
                }
            }
            return RedirectToAction("Profile", "Person", new { id = friendToRemove });
        }

        //Hämtar prfilbild som FileContentResult för att visas i den vyn där metoden anropats.
        [AllowAnonymous]
        public FileContentResult LoadPicture(int id)
        {
            byte[] image = personRepository.GetPictureById(id);
            if (image != null)
            {
                return new FileContentResult(image, "image/jpeg");
            }
            return null;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> UpdateProfile(ProfileViewModel profileModel)
        {
            int currentUser = personRepository.GetIdByUserIdentityEmail((string)User.Identity.Name);
            Person personToUpdate = personRepository.GetPersonById(currentUser);
            personToUpdate.FirstName = profileModel.FirstName;
            personToUpdate.LastName = profileModel.LastName;
            personToUpdate.Description = profileModel.Description;
            personToUpdate.AccountHidden = profileModel.AccountHidden;

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(personToUpdate);
                    await _context.SaveChangesAsync();
                }
                catch (Exception)
                {
                    TempData["ProcessMessage"] = "Could not update profile";
                    return PartialView("Exception");
                }
            }

            return RedirectToAction("MyProfile");
        }

        //Uppdaterar profilbilden till användarens valda bild
        [ValidateAntiForgeryToken]
        public IActionResult UploadImage()
        {
            foreach (var file in Request.Form.Files) 
                //loopar igenom filerna som lagts in, ifall man lagt in flera bilder så kommer den senast inlagda vara den som sparas
            {
                int currentUser = personRepository.GetIdByUserIdentityEmail((string)User.Identity.Name);
                Person personToUpdate = personRepository.GetPersonById(currentUser);

                System.IO.MemoryStream ms = new MemoryStream();
                file.CopyTo(ms);
                personToUpdate.Picture = ms.ToArray();
                    //skapar en memorystream som hämtar in bildfilen och lägger den som användarens nya bild

                ms.Close();
                ms.Dispose();
                try
                {
                    _context.Update(personToUpdate);
                    _context.SaveChanges();
                }
                catch(Exception)
                {
                    TempData["ProcessMessage"] = "Could not update profile picture, please try again";
                    return PartialView("Exception");
                }
                
            }
            return RedirectToAction("MyProfile");
        }

        public PartialViewResult UpdatePostWall(int id)
        {
            List<Post> posts = postRepository.GetAllPostsByPersonId(id);
            PostUserViewModel postUserViewModel = CreatePostUserViewModel(posts, id);

DatingApp/Controllers/RequestController.cs
using DataLayer;
using DataLayer.Models;
using DataLayer.Repositories;
using DatingApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace DatingApp.Controllers
{
    public class RequestController : Controller
    {
        private readonly DatingAppContext _context;
        private PersonRepository personRepository;
        private FriendRequestRepository requestRepository;

        public RequestController(DatingAppContext context)
        {
            _context = context;
            personRepository = new PersonRepository(context);
            requestRepository = new FriendRequestRepository(context);
        }

        //Hämtar alla vänförfrågningar och returnerar en av två partialviews beroende på om det finns några vänförfrågningar. 
        [AllowAnonymous]
        [HttpGet]
        public PartialViewResult GetFriendRequests()
        {
            string email = User.Identity.Name;
            int reciever = personRepository.GetIdByUserIdentityEmail(email);
            List<FriendRequest> requests = requestRepository.GetAllRequestsSentToUser(reciever);
            if (requests.Count > 0)
            {
                IEnumerable<RequestViewModel> model = requests.Select((r) => new RequestViewModel()
                {
                    SenderId = r.SenderId,
                    Sender = personRepository.GetPersonById(r.SenderId),
                    FullName = r.Sender.FirstName + " " + r.Sender.LastName
                });
                return PartialView("_Requests", model);
            }
            else
            {
                return PartialView("_NoRequests");
            }
        }

        //Hämtar antalet vänförfrågningar och returnerar resultatet som JSON
        [HttpPost]
        public ActionResult GetNumberOfRequests()
        {
            int id = personRepository.GetIdByUserIdentityEmail(User.Identity.Name);
            List<FriendRequest> requests = requestRepository.GetAllRequestsSentToUser(id);
            return Json(new {data = requests.Count });
        }

        public ActionResult AcceptRequest(int senderId)
        {
            int receiverId = personRepository.GetIdByUserIdentityEmail(User.Identity.Name);

            List<FriendRequest> requests = requestRepository.GetAllRequestsSentToUser(receiverId);
            
            foreach(FriendRequest fr in requests) //Loopar genom alla vänförfrågningar användaren har fått
            {
                if(fr.SenderId == senderId && fr.ReceiverId == receiverId) //Kontrollerar att sändare och mottagare stämmer
                {
                    fr.Accepted = true;
                    try
                    {
                        _context.Update(fr);
                        _context.SaveChanges();
                    }
                    catch (Exception)
                    {
                        TempData["ProcessMessage"] = "Could not update profile picture, please try again";
                        return PartialView("Exception");
                    }
                }
            }
            return RedirectToAction("Profile", "Person", new { id = senderId });
        }   
        
        public ActionResult DeclineRequest(int senderId)
        {
            int receiverId = personRepository.GetIdByUserIdentityEmail(User.Identity.Name);
            List<FriendRequest> requests = requestRepository.GetAllRequestsSentToUser(receiverId);

            foreach(FriendRequest fr in requests)
            {
                if (fr.SenderId.Equals(senderId) && fr.ReceiverId.Equals(receiverId))
                {
                    try
                    {
                        _context.Remove(fr);
                        _context.SaveChanges();
                    }
                    catch (Exception)
                    {
                        TempData["ProcessMessage"] = "Could not decline friend, try again later";
                        return PartialView("Exception");
                    }
                }
            }
            return RedirectToAction("Profile", "Person", new { id = senderId });
        }

        public ActionResult SendRequest(int receiverId)
        {
            int senderId = personRepository.GetIdByUserIdentityEmail(User.Identity.Name);
            FriendRequest friendRequest = new FriendRequest //Skapar ny vänförfrågan
            {
                Sender = personRepository.GetPersonById(senderId),
                SenderId = senderId,
                Receiver = personRepository.GetPersonById(receiverId),
                ReceiverId = receiverId,
                Accepted = false
            };
            try
            {
                _context.Add(friendRequest);
                _context.SaveChanges();
            }
            catch (Exception)
            {
                TempData["ProcessMessage"] = "Could not send request, try again later";
                return PartialView("Exception");
            }
            return RedirectToAction("Profile", "Person", new { id = receiverId });
        }

        //Avbryter och tar bort en förfrågan användaren har skickat
        public ActionResult CancelRequest(int receiverId)
        {
            int senderId = personRepository.GetIdByUserIdentityEmail(User.Identity.Name);
            if (requestRepository.FriendRequestOutgoing(senderId, receiverId))
            {
                //Hämtar alla förfrågningar användaren har skickat
                List<FriendRequest> requests = requestRepository.GetAllRequestsSentByUser(senderId); 
                foreach (FriendRequest r in requests)
                {
                    if (r.ReceiverId == receiverId && r.SenderId == senderId)
                    {
                        try
                        {
                            _context.Remove(r);
                            _context.SaveChanges();
                        }
                        catch (Exception)
                        {
                            TempData["ProcessMessage"] = "Could not cancel request, try again later";
                            return PartialView("Exception");
                        }
                    }
                }
            }
            return RedirectToAction("Profile", "Person", new { id = receiverId });
        }
    }
}

DatingApp/Views/Person/Exception.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DatingApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <div id="exceptionDiv">
        <div id="exception">
            <h2>@TempData["ProcessMessage"]</h2>
            <a asp-area="" asp-controller="Home" asp-action="Index">Return to homepage</a>
        </div>
    </div>
</body>
</html>

DatingApp/Views/Person/MyProfile.cshtml
@model DatingApp.Models.ProfileViewModel
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@{
    ViewData["Title"] = "My Profile";
}



@if (SignInManager.IsSignedIn(User))
{
    <h1 class="myprofile">My Profile</h1>
    <br />
    <div>
        <div class="myprofile">
            <img width="200" height="200" src="@Url.Action("LoadPicture", "Person", new { id = @Model.PersonId })" />
        </div>
        <br />
        <form class="text-center" asp-action="UploadImage"
              asp-controller="Person"
              method="post"
              enctype="multipart/form-data">
            <input type="file" id="file1"
                   name="file1"
                   multiple="multiple" />
                <button type="submit" class="btn btn-primary">Upload File</button>
        </form>

        <form asp-action="UpdateProfile" class="myprofile" id="myProfile" enctype="multipart/form-data">
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="hideAccount">
                    Hide account from other users
                    <input asp-for="AccountHidden" type="checkbox">
                    <span class="hideAccountCheckmark"></span>
                </label>
            </div>

            <div class="form-group">
                <input id="editProfile" type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>

        <ul class="nav myprofile">
            <li class="nav-item"><a class="nav-link" id="password" href="/Identity/Account/Manage/ChangePassword">Manage password</a></li>
        </ul>
    </div>

    <div class="profileWall">
        <div class="col-lg-5" id="PostWall">
            @await Html.PartialAsync("/Views/Post/_Post.cshtml", Model.Posts)
            <hr />
        </div>
        <div class="col-lg-5" id="FriendWall">
            @await Html.PartialAsync("_Friend.cshtml", Model.Friends)
            <hr />
        </div>
    </div>

}
else
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
    </li>
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DatingApp/Views/Person/Profile.cshtml
@model DatingApp.Models.ProfileViewModel
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@{
    ViewData["Title"] = "Profile";
}



@if (SignInManager.IsSignedIn(User))
{
    <div class="text-center">
        <img width="200" height="200" src="@Url.Action("LoadPicture", "Person", new { id = @Model.PersonId })" />
        <h2>@Model.FirstName @Model.LastName</h2>
        <p>@Model.Description</p>

        @switch (ViewBag.PersonRelation)
        {
            case "Friends":
                <input type="button" class="btn btn-danger" id="FriendBtn" value="Remove Friend"
                       onclick="location.href='@Url.Action("RemoveFriend", "Person", new {friendToRemove = Model.PersonId })'" />
                break;
            case "IncomingRequest":
                <div>
                    <input type="button" class="btn btn-success" id="AcceptBtn" value="Accept"
                           onclick="location.href='@Url.Action("AcceptRequest", "Request", new {senderId = Model.PersonId })'" />
                    <input type="button" class="btn btn-danger" id="DeclineBtn" value="Decline"
                           onclick="location.href='@Url.Action("DeclineRequest", "Request", new {senderId = Model.PersonId })'" />
                </div>
                break;
            case "OutgoingRequest":
                <input type="button" class="btn btn-warning" id="FriendBtn" value="Cancel Friend Request"
                       onclick="location.href='@Url.Action("CancelRequest", "Request", new {receiverId = Model.PersonId })'" />
                break;
            case "NotFriends":
                <input type="button" class="btn btn-info" id="FriendBtn" value="Send Friend Request"
                       onclick="location.href='@Url.Action("SendRequest", "Request", new {receiverId = Model.PersonId })'" />
                break;
            default:
                break;
        }

    </div>
    <div class="col-lg-5" id="PostWall">
        @await Html.PartialAsync("/Views/Post/_Post.cshtml", Model.Posts)
        <hr />
    </div>
}
else
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
    </li>
}

DatingApp/Views/Person/_Friend.cshtml
@model DatingApp.Models.FriendUserViewModel
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    ViewData["Title"] = "Friend";
}


@if (SignInManager.IsSignedIn(User))
{
    <h2>Friends</h2>
    if (Model != null)
    {
        @foreach (var item in Model.Friends)
        {
            <div class="card post mb-3">
                <div class="card-header">
                    <div class="media">
                        @if (@item.SecondPerson.PersonId == Model.PersonId)
                        {
                            <a href="@Url.Action("Profile", "Person", new { id = item.FirstPerson.PersonId })" class="card-link">
                                <img class="mr-1" src="@Url.Action("LoadPicture", "Person", new { id = item.FirstPerson.PersonId })" height="32" width="32" />
                                <span class="badge badge-light">@item.FirstPerson.FirstName @item.FirstPerson.LastName</span>
                            </a>
                        }
                        @if (item.FirstPerson.PersonId == Model.PersonId)
                        {
                            <a href="@Url.Action("Profile", "Person", new { id = item.SecondPerson.PersonId })" class="card-link">
                                <img class="mr-1" src="@Url.Action("LoadPicture", "Person", new { id = item.SecondPerson.PersonId })" height="32" width="32" />
                                <span class="badge badge-light">@item.SecondPerson.FirstName @item.SecondPerson.LastName</span>
                            </a>
                        }
                    </div>
                </div>
            </div>
        }
    }
    else
    {
        <h2>Du har inga vänner..</h2>
    }
}
else
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
    </li>
}